name: ai_farmer_assistant
description: "AI Farmer Assistant App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  http: ^1.2.0
  shared_preferences: ^2.2.2
  flutter_image_compress: ^2.1.0
  http_parser: ^4.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true